######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 21 11:43:16 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ex06opengl.h ex06viewer.h
SOURCES += ex06.cpp ex06opengl.cpp ex06viewer.cpp
RESOURCES += ex06.qrc
